# Generated by Django 5.1.1 on 2024-09-08 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('dr', 'Dr.'), ('prof_dr.', 'Prof. Dr.'), ('dr_rer_nat', 'Dr. rer. nat')], max_length=20)),
                ('speciality', models.CharField(choices=[('allgemeinedizin', 'Allgemeinedizin'), ('radiologe', 'Radiologe'), ('hautarzt', 'Hautarzt')], max_length=50)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
